// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrnog-EDvxsmXE_RF8u6x5YDyu8yo48Pw',
    appId: '1:227896787399:web:c3ccb884f7b7c028e759e2',
    messagingSenderId: '227896787399',
    projectId: 'pantry-share',
    authDomain: 'pantry-share.firebaseapp.com',
    storageBucket: 'pantry-share.firebasestorage.app',
    measurementId: 'G-QYPMPMH61E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN08h8Fc1Zw1Sq6uVgNErRnhSC6sQTOs4',
    appId: '1:227896787399:android:7d91c2e17b40bb73e759e2',
    messagingSenderId: '227896787399',
    projectId: 'pantry-share',
    storageBucket: 'pantry-share.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfwNfggBk9-XOoQwgjiZHKIf80OcvxdXI',
    appId: '1:227896787399:ios:007b4b98feb413cce759e2',
    messagingSenderId: '227896787399',
    projectId: 'pantry-share',
    storageBucket: 'pantry-share.firebasestorage.app',
    iosBundleId: 'com.example.pantryShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfwNfggBk9-XOoQwgjiZHKIf80OcvxdXI',
    appId: '1:227896787399:ios:007b4b98feb413cce759e2',
    messagingSenderId: '227896787399',
    projectId: 'pantry-share',
    storageBucket: 'pantry-share.firebasestorage.app',
    iosBundleId: 'com.example.pantryShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrnog-EDvxsmXE_RF8u6x5YDyu8yo48Pw',
    appId: '1:227896787399:web:b7705f2cf9f20eabe759e2',
    messagingSenderId: '227896787399',
    projectId: 'pantry-share',
    authDomain: 'pantry-share.firebaseapp.com',
    storageBucket: 'pantry-share.firebasestorage.app',
    measurementId: 'G-WDDNLSML8L',
  );
}
